add kubernetes deploy example
traum-ferienwohnungen/opsgenie-heartbeat-proxy pull request #4
Opened 2018-08-24 06:47 UTC by TheKangaroo

I deployed the heartbeat proxy to kubernetes yesterday and wanted to share the examples with you.

2018-08-24 11:59 UTC, jayme-github requested changes
Hi,
thank you very much for your contribution!

I will forward this to @NilsGriebner for further review and merge. Do you mind adding a small note to the README regarding your example?

2018-08-24 11:59 UTC, jayme-github commented on examples/k8sdeploy.yaml
> +          image: registry.gitlab.dm-drogeriemarkt.com/docker/opsgenie-heartbeat-proxy
Could you please exchange the `image` for the autobuild one from https://hub.docker.com/r/traumfewo/opsgenie-heartbeat-proxy/

2018-08-24 11:59 UTC, jayme-github commented on examples/k8sdeploy.yaml
> +  namespace: monitoring
Please remove the `namespace:` to make this a little more generic.

2018-08-24 17:44 UTC, NilsGriebner commented
@TheKangaroo thanks for your contribution :) I agree with @jayme-github points. This changes would be great. We use resource limits in our deployment, maybe we should add it here too. What do you think?

2018-08-24 17:48 UTC, NilsGriebner requested changes

2018-08-24 17:48 UTC, NilsGriebner commented on examples/k8sdeploy.yaml
> +#          - name: DEBUG
I think this could be removed, because it's for debugging only.

2018-08-27 18:17 UTC, TheKangaroo commented
Hey @NilsGriebner, @jayme-github , sorry for the delay. I fixed the image path and removed the namespace.
I also added the limits. We use them too in our setup, but I'm not 100% sure if we really should add them to a simple example. I'm fine with both ways, you guys decide ;-)

I added some lines about kubernetes to the readme too.
What do you think?

2018-08-27 19:00 UTC, NilsGriebner commented
Hi @TheKangaroo looks good to me now :) I will give it a try in our playground and merge if I don't spot any issues.

Thanks aggain, great work :)

2018-08-27 19:01 UTC, NilsGriebner approved these changes

2018-08-27 21:33 UTC, merged